export enum EntityName{
User="user",
Admin="admin",
Product="product",
blog="blog",
Basket="basket",
Order="order",
Payment="payment",
OrderItem="orderItem",
Discount="discount",
Address="address",
BlogComments="blogComments",
Otp="otp",
Product_Audit="product_audit",
ProductDetail="product_detail",
}